/**
 * This class is the template view for the application.
 */
Ext.define('Admin.view.main.vehiclemonitoringmain.historytrace.HistorySearchForm', {
    extend: 'Ext.form.Panel',
    requires: [
        'Ext.layout.container.HBox',
        'Ext.form.field.Date',
        'Ext.form.FieldContainer',
        'Ext.form.field.ComboBox',
        'Ext.form.FieldSet',
        'Admin.view.main.vehiclemonitoringmain.historytrace.HistoryTraceController'
    ],
    reference:'historySearchForm',
    bodyPadding: 1,
    header: false,
    fieldDefaults: {
        // labelAlign: 'right',
        labelWidth: 65,
        margin: '0 0 0 0', //label和上一个输入框的样式，间隔5
        msgTarget: Ext.supports.Touch ? 'side' : 'qtip'
    },
    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    margin: '0 5', //对panel生效
    height: 45,
    items: [
	{
        xtype: 'form',
        layout: {
	        type: 'table',
	        columns: 6,
	        
    	},
//        flex:4,
        items: [{
        		xtype:'displayfield',
        		fieldLabel: '开始时间',
        		width:70,
//    			margin:'3 0 0 0'
        	},{
	            name:'sDate',
//	            fieldLabel: '开始时间',
	            hideLabel:true,
	            xtype: 'datefield',
	            margin:'-6 0 0 0',
				format: 'Y-m-d',
				width:140,
				maxValue: new Date(),
				value:  GetYesterDayTime(),
				id:'mainVehMoniTraceStartDate',
        	},
        	{
                xtype: 'fieldcontainer',
                layout: 'hbox',
                margin:'-6 0 0 0',
                items: [{
                    xtype: 'combobox',
                    name: 'sHour',
                    displayField: 'time',
                    valueField: 'id',
                    queryMode: 'local',
                    emptyText: '时',
                    hideLabel: true,
                    margin: '0 4 ',
                    width:70,
                    allowBlank: false,
                    forceSelection: true,
                    value : '0',
                    store: {
                    	fields:['id', 'time'],
    	            	data : [
    	            	        {'id': '0', 'time': '00'},
    					        {'id': '1', 'time': '01'},
    					        {'id': '2', 'time': '02'},
    					        {'id': '3', 'time': '03'},
    					        {'id': '4', 'time': '04'},
    					        {'id': '5', 'time': '05'},
    					        {'id': '6', 'time': '06'},
    					        {'id': '7', 'time': '07'},
    					        {'id': '8', 'time': '08'},
    					        {'id': '9', 'time': '09'},
    					        {'id': '10', 'time': '10'},
    					        {'id': '11', 'time': '11'},
    					        {'id': '12', 'time': '12'},
    					        {'id': '13', 'time': '13'},
    					        {'id': '14', 'time': '14'},
    					        {'id': '15', 'time': '15'},
    					        {'id': '16', 'time': '16'},
    					        {'id': '17', 'time': '17'},
    					        {'id': '18', 'time': '18'},
    					        {'id': '19', 'time': '19'},
    					        {'id': '20', 'time': '20'},
    					        {'id': '21', 'time': '21'},
    					        {'id': '22', 'time': '22'},
    					        {'id': '23', 'time': '23'},
    					]
                    }
                },
                {
                    xtype: 'combobox',
                    name: 'sMinute',
                    displayField: 'time',
                    valueField: 'id',
                    queryMode: 'local',
                    emptyText: '分',
                    hideLabel: true,
                    margin: '0 4 0 0',
                    width:70,
                    allowBlank: false,
                    forceSelection: true,
                    value : '0',
                    store: {
                    	fields:['id', 'time'],
    	            	data : [
    	            	        {'id': '0', 'time': '00'},
    					        {'id': '1', 'time': '01'},
    					        {'id': '2', 'time': '02'},
    					        {'id': '3', 'time': '03'},
    					        {'id': '4', 'time': '04'},
    					        {'id': '5', 'time': '05'},
    					        {'id': '6', 'time': '06'},
    					        {'id': '7', 'time': '07'},
    					        {'id': '8', 'time': '08'},
    					        {'id': '9', 'time': '09'},
    					        {'id': '10', 'time': '10'},
    					        {'id': '11', 'time': '11'},
    					        {'id': '12', 'time': '12'},
    					        {'id': '13', 'time': '13'},
    					        {'id': '14', 'time': '14'},
    					        {'id': '15', 'time': '15'},
    					        {'id': '16', 'time': '16'},
    					        {'id': '17', 'time': '17'},
    					        {'id': '18', 'time': '18'},
    					        {'id': '19', 'time': '19'},
    					        {'id': '20', 'time': '20'},
    					        {'id': '21', 'time': '21'},
    					        {'id': '22', 'time': '22'},
    					        {'id': '23', 'time': '23'},
    					        {'id': '24', 'time': '24'},
    					        {'id': '25', 'time': '25'},
    					        {'id': '26', 'time': '26'},
    					        {'id': '27', 'time': '27'},
    					        {'id': '28', 'time': '28'},
    					        {'id': '29', 'time': '29'},
    					        {'id': '30', 'time': '30'},
    					        {'id': '31', 'time': '31'},
    					        {'id': '32', 'time': '32'},
    					        {'id': '33', 'time': '33'},
    					        {'id': '34', 'time': '34'},
    					        {'id': '35', 'time': '35'},
    					        {'id': '36', 'time': '36'},
    					        {'id': '37', 'time': '37'},
    					        {'id': '38', 'time': '38'},
    					        {'id': '39', 'time': '39'},
    					        {'id': '40', 'time': '40'},
    					        {'id': '41', 'time': '41'},
    					        {'id': '42', 'time': '42'},
    					        {'id': '43', 'time': '43'},
    					        {'id': '44', 'time': '44'},
    					        {'id': '45', 'time': '45'},
    					        {'id': '46', 'time': '46'},
    					        {'id': '47', 'time': '47'},
    					        {'id': '48', 'time': '48'},
    					        {'id': '49', 'time': '49'},
    					        {'id': '50', 'time': '50'},
    					        {'id': '51', 'time': '51'},
    					        {'id': '52', 'time': '52'},
    					        {'id': '53', 'time': '53'},
    					        {'id': '54', 'time': '54'},
    					        {'id': '55', 'time': '55'},
    					        {'id': '56', 'time': '56'},
    					        {'id': '57', 'time': '57'},
    					        {'id': '58', 'time': '58'},
    					        {'id': '59', 'time': '59'},
    					        
    					]
                    }
                },
                {
                    xtype: 'combobox',
                    name: 'sSecond',
                    displayField: 'time',
                    valueField: 'id',
                    queryMode: 'local',
                    emptyText: '秒',
                    hideLabel: true,
                    width:70,
                    allowBlank: false,
                    forceSelection: true,
                    value : '0',
                    store: {
                    	fields:['id', 'time'],
    	            	data : [
							{'id': '0', 'time': '00'},
							{'id': '1', 'time': '01'},
							{'id': '2', 'time': '02'},
							{'id': '3', 'time': '03'},
							{'id': '4', 'time': '04'},
							{'id': '5', 'time': '05'},
							{'id': '6', 'time': '06'},
							{'id': '7', 'time': '07'},
							{'id': '8', 'time': '08'},
							{'id': '9', 'time': '09'},
							{'id': '10', 'time': '10'},
							{'id': '11', 'time': '11'},
							{'id': '12', 'time': '12'},
							{'id': '13', 'time': '13'},
							{'id': '14', 'time': '14'},
							{'id': '15', 'time': '15'},
							{'id': '16', 'time': '16'},
							{'id': '17', 'time': '17'},
							{'id': '18', 'time': '18'},
							{'id': '19', 'time': '19'},
							{'id': '20', 'time': '20'},
							{'id': '21', 'time': '21'},
							{'id': '22', 'time': '22'},
							{'id': '23', 'time': '23'},
							{'id': '24', 'time': '24'},
							{'id': '25', 'time': '25'},
							{'id': '26', 'time': '26'},
							{'id': '27', 'time': '27'},
							{'id': '28', 'time': '28'},
							{'id': '29', 'time': '29'},
							{'id': '30', 'time': '30'},
							{'id': '31', 'time': '31'},
							{'id': '32', 'time': '32'},
							{'id': '33', 'time': '33'},
							{'id': '34', 'time': '34'},
							{'id': '35', 'time': '35'},
							{'id': '36', 'time': '36'},
							{'id': '37', 'time': '37'},
							{'id': '38', 'time': '38'},
							{'id': '39', 'time': '39'},
							{'id': '40', 'time': '40'},
							{'id': '41', 'time': '41'},
							{'id': '42', 'time': '42'},
							{'id': '43', 'time': '43'},
							{'id': '44', 'time': '44'},
							{'id': '45', 'time': '45'},
							{'id': '46', 'time': '46'},
							{'id': '47', 'time': '47'},
							{'id': '48', 'time': '48'},
							{'id': '49', 'time': '49'},
							{'id': '50', 'time': '50'},
							{'id': '51', 'time': '51'},
							{'id': '52', 'time': '52'},
							{'id': '53', 'time': '53'},
							{'id': '54', 'time': '54'},
							{'id': '55', 'time': '55'},
							{'id': '56', 'time': '56'},
							{'id': '57', 'time': '57'},
							{'id': '58', 'time': '58'},
							{'id': '59', 'time': '59'},
    					]
                    }
                },
                ]
            },
            {
        		fieldLabel: '结束时间',
        		xtype:'displayfield',
        		width:70,
        		margin:'0 0 0 15'
        	},{
	            name:'eDate',
//	            fieldLabel: '结束时间',
	            hideLabel:true,
	            xtype: 'datefield',
				format: 'Y-m-d',
				id:'mainVehMoniTraceEndDate',
				width:140,
				maxValue: new Date(),
				value : GetYesterDayTime(),
				margin:'-6 0 0 0'
	        	},
	          	{
	                xtype: 'fieldcontainer',
	                layout: 'hbox',
	                margin:'-6 0 0 0',
	                items: [{
	                    xtype: 'combobox',
	                    name: 'eHour',
	                    displayField: 'time',
	                    valueField: 'id',
	                    queryMode: 'local',
	                    emptyText: '时',
	                    hideLabel: true,
	                    margin: '0 4',
	                    width:70,
	                    allowBlank: false,
	                    forceSelection: true,
	                    value : '23',
	                    store: {
	                    	fields:['id', 'time'],
	    	            	data : [
									{'id': '0', 'time': '00'},
									{'id': '1', 'time': '01'},
									{'id': '2', 'time': '02'},
									{'id': '3', 'time': '03'},
									{'id': '4', 'time': '04'},
									{'id': '5', 'time': '05'},
									{'id': '6', 'time': '06'},
									{'id': '7', 'time': '07'},
									{'id': '8', 'time': '08'},
									{'id': '9', 'time': '09'},
									{'id': '10', 'time': '10'},
									{'id': '11', 'time': '11'},
									{'id': '12', 'time': '12'},
									{'id': '13', 'time': '13'},
									{'id': '14', 'time': '14'},
									{'id': '15', 'time': '15'},
									{'id': '16', 'time': '16'},
									{'id': '17', 'time': '17'},
									{'id': '18', 'time': '18'},
									{'id': '19', 'time': '19'},
									{'id': '20', 'time': '20'},
									{'id': '21', 'time': '21'},
									{'id': '22', 'time': '22'},
									{'id': '23', 'time': '23'},
									
	    					]
	                    }
	                },
	                {
	                    xtype: 'combobox',
	                    name: 'eMinute',
	                    displayField: 'time',
	                    valueField: 'id',
	                    queryMode: 'local',
	                    emptyText: '分',
	                    hideLabel: true,
	                    margin: '0 4 0 0',
	                    width:70,
	                    allowBlank: false,
	                    forceSelection: true,
	                    value : '59',
	                    store: {
	                    	fields:['id', 'time'],
	    	            	data : [
	    	            	        {'id': '0', 'time': '00'},
	    					        {'id': '1', 'time': '01'},
	    					        {'id': '2', 'time': '02'},
	    					        {'id': '3', 'time': '03'},
	    					        {'id': '4', 'time': '04'},
	    					        {'id': '5', 'time': '05'},
	    					        {'id': '6', 'time': '06'},
	    					        {'id': '7', 'time': '07'},
	    					        {'id': '8', 'time': '08'},
	    					        {'id': '9', 'time': '09'},
	    					        {'id': '10', 'time': '10'},
	    					        {'id': '11', 'time': '11'},
	    					        {'id': '12', 'time': '12'},
	    					        {'id': '13', 'time': '13'},
	    					        {'id': '14', 'time': '14'},
	    					        {'id': '15', 'time': '15'},
	    					        {'id': '16', 'time': '16'},
	    					        {'id': '17', 'time': '17'},
	    					        {'id': '18', 'time': '18'},
	    					        {'id': '19', 'time': '19'},
	    					        {'id': '20', 'time': '20'},
	    					        {'id': '21', 'time': '21'},
	    					        {'id': '22', 'time': '22'},
	    					        {'id': '23', 'time': '23'},
	    					        {'id': '24', 'time': '24'},
									{'id': '25', 'time': '25'},
									{'id': '26', 'time': '26'},
									{'id': '27', 'time': '27'},
									{'id': '28', 'time': '28'},
									{'id': '29', 'time': '29'},
									{'id': '30', 'time': '30'},
									{'id': '31', 'time': '31'},
									{'id': '32', 'time': '32'},
									{'id': '33', 'time': '33'},
									{'id': '34', 'time': '34'},
									{'id': '35', 'time': '35'},
									{'id': '36', 'time': '36'},
									{'id': '37', 'time': '37'},
									{'id': '38', 'time': '38'},
									{'id': '39', 'time': '39'},
									{'id': '40', 'time': '40'},
									{'id': '41', 'time': '41'},
									{'id': '42', 'time': '42'},
									{'id': '43', 'time': '43'},
									{'id': '44', 'time': '44'},
									{'id': '45', 'time': '45'},
									{'id': '46', 'time': '46'},
									{'id': '47', 'time': '47'},
									{'id': '48', 'time': '48'},
									{'id': '49', 'time': '49'},
									{'id': '50', 'time': '50'},
									{'id': '51', 'time': '51'},
									{'id': '52', 'time': '52'},
									{'id': '53', 'time': '53'},
									{'id': '54', 'time': '54'},
									{'id': '55', 'time': '55'},
									{'id': '56', 'time': '56'},
									{'id': '57', 'time': '57'},
									{'id': '58', 'time': '58'},
									{'id': '59', 'time': '59'},
	    					]
	                    }
	                },
	                {
	                    xtype: 'combobox',
	                    name: 'eSecond',
	                    displayField: 'time',
	                    valueField: 'id',
	                    queryMode: 'local',
	                    emptyText: '秒',
	                    hideLabel: true,
	                    margin: '0 6 0 0',
	                    width:70,
	                    allowBlank: false,
	                    forceSelection: true,
	                    value : '59',
	                    store: {
	                    	fields:['id', 'time'],
	    	            	data : [
	    	            	        {'id': '0', 'time': '00'},
	    					        {'id': '1', 'time': '01'},
	    					        {'id': '2', 'time': '02'},
	    					        {'id': '3', 'time': '03'},
	    					        {'id': '4', 'time': '04'},
	    					        {'id': '5', 'time': '05'},
	    					        {'id': '6', 'time': '06'},
	    					        {'id': '7', 'time': '07'},
	    					        {'id': '8', 'time': '08'},
	    					        {'id': '9', 'time': '09'},
	    					        {'id': '10', 'time': '10'},
	    					        {'id': '11', 'time': '11'},
	    					        {'id': '12', 'time': '12'},
	    					        {'id': '13', 'time': '13'},
	    					        {'id': '14', 'time': '14'},
	    					        {'id': '15', 'time': '15'},
	    					        {'id': '16', 'time': '16'},
	    					        {'id': '17', 'time': '17'},
	    					        {'id': '18', 'time': '18'},
	    					        {'id': '19', 'time': '19'},
	    					        {'id': '20', 'time': '20'},
	    					        {'id': '21', 'time': '21'},
	    					        {'id': '22', 'time': '22'},
	    					        {'id': '23', 'time': '23'},
	    					        {'id': '24', 'time': '24'},
									{'id': '25', 'time': '25'},
									{'id': '26', 'time': '26'},
									{'id': '27', 'time': '27'},
									{'id': '28', 'time': '28'},
									{'id': '29', 'time': '29'},
									{'id': '30', 'time': '30'},
									{'id': '31', 'time': '31'},
									{'id': '32', 'time': '32'},
									{'id': '33', 'time': '33'},
									{'id': '34', 'time': '34'},
									{'id': '35', 'time': '35'},
									{'id': '36', 'time': '36'},
									{'id': '37', 'time': '37'},
									{'id': '38', 'time': '38'},
									{'id': '39', 'time': '39'},
									{'id': '40', 'time': '40'},
									{'id': '41', 'time': '41'},
									{'id': '42', 'time': '42'},
									{'id': '43', 'time': '43'},
									{'id': '44', 'time': '44'},
									{'id': '45', 'time': '45'},
									{'id': '46', 'time': '46'},
									{'id': '47', 'time': '47'},
									{'id': '48', 'time': '48'},
									{'id': '49', 'time': '49'},
									{'id': '50', 'time': '50'},
									{'id': '51', 'time': '51'},
									{'id': '52', 'time': '52'},
									{'id': '53', 'time': '53'},
									{'id': '54', 'time': '54'},
									{'id': '55', 'time': '55'},
									{'id': '56', 'time': '56'},
									{'id': '57', 'time': '57'},
									{'id': '58', 'time': '58'},
									{'id': '59', 'time': '59'},
	    					]
	                    }
	                },
	                ]
	            },
        ]
	},
	{
    	xtype:'container',
    	flex:1,
    	items:[{
    		xtype:'button',
    		text: '<i class="fa fa-search"></i>&nbsp;查询',
    		style:'float:right',
    		id:'mainVehMoniHistorySearch',
//    		handler:'onClickSearch',
    		listeners:{
    			click:'onClickSearch'
    		},
//    		margin: '35 0 0 50',
    		tooltip: '建议：为避免长时间等待，搜索的历史记录时间间隔请不要大于3天。',
    	}]
	}
    ],
    
    initComponent: function() {
        this.callParent();
    }
   
});

function GetYesterDayTime() {
	var dd = new Date();
	dd.setDate(dd.getDate()-1);
	var y = dd.getFullYear();
	var m = dd.getMonth()+1;
	if(m < 10){
		m = '0' + m;
	}
	var d = dd.getDate();
	if(d < 10){
		d = '0' + d;
	}
	return y+"-"+m+"-"+d;
}

