spring:
  application:
    name: zipkin-server
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    stream:
      kafka:
        binder:
          zk-nodes: localhost:2181
  jmx:
    default-domain: ${spring.application.name}
#  datasource:
#    schema: classpath:/mysql.sql
#    url: jdbc:mysql://localhost:3306/zipkin
#    username: root
#    password: root
#    continue-on-error: true
#    initialize: true
  sleuth:
    enabled: false


zipkin:
  storage:
    type: cassandra3
    cassandra3:
      contactPoints: localhost
#      username: crt_tsp_sa
#      password: crt_tsp_sa


server:
  port: 9411
